---
- name: install git
  apt: name=git state=present

- name: creating known_hosts
  file: path=~/.ssh/known_hosts 
        state=touch 
        mode=0644

- name: Add GitHub key
  shell: ssh-keyscan github.com >> ~/.ssh/known_hosts

- name: Add bitbuckets key
  shell: ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
