- name: Route 53 info
  hosts: 127.0.0.1
  tasks:
    - route53:
        command=get
        zone=
        record=
        type=CNAME
      register: rec
    - debug: msg="Value is {{ rec.set.value }}"

- name: Route 53 info
  hosts: 127.0.0.1
  tasks:
    - route53:
         command=create
         zone=
         record=
         type=CNAME
         ttl=60
         value="example555.com"
         overwrite=true