- name: Route 53 info
  hosts: 127.0.0.1
  tasks:
    - route53:
        command=get
        zone=michaldec.info
        record=test.michaldec.info
        type=CNAME
      register: rec
    - debug: msg="Value is {{ rec.set.value }}"

- name: Route 53 info
  hosts: 127.0.0.1
  tasks:
    - route53:
         command=create
         zone=michaldec.info
         record=test.michaldec.info
         type=CNAME
         ttl=60
         value="example123.com"
         overwrite=true