---
- name: check if SWAP file exists
  stat: path=/swapfile  
  register: swap_exist

- name: creating SWAP file
  command: dd if=/dev/zero of=/swapfile bs=1024 count=1024k
  when: swap_exist.stat.exists == False    
 
- name: preparing SWAP area
  command: mkswap /swapfile  
  when: swap_exist.stat.exists == False

- name: activate SWAP
  command: swapon /swapfile
  when: swap_exist.stat.exists == False

- name: add entry to /etc/fstab
  mount: name=none src=/swapfile fstype=swap opts=sw state=present

- name: improve performance
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = 0"

- name: reload sysctl
  command: sysctl -p

- name: secure swap
  file: path=/swapfile owner=root group=root mode=0600
