---
- name: creating SWAP file
  command: dd if=/dev/zero of=/swapfile bs=1024 count=1024k
  when:
    - file: /swapfile state=absent
  
- name: preparing SWAP area
  command: mkswap /swapfile  

- name: activate SWAP
  command: swapon /swapfile

- name: add entry to /etc/fstab
  mount: name=none src=/swapfile fstype=swap opts=sw state=present

- name: improve performance
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = 0"

- name: reload sysctl
  command: sysctl -p

- name: secure swap
  file: path=/swapfile owner=root group=root mode=0600
