- name: "Create security group"
  local_action:
    module: ec2_group
    name: "my_security_group"
    description: Security group configuration example
    region: "{{ aws_region }}"
    vpc_id: "{{ aws_vpc_id }}"
    purge_rules: false
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

- name: "Create instances"
  local_action:
    module: ec2
    region: "{{ aws_region }}"
    key_name: "{{ aws_key_pair }}"
    group: ["my_security_group"]
    instance_type: "t2.small"
    image: "{{ aws_ami_id }}"
    wait: yes
    count: 1
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    instance_tags:
      Name: "NewInstance"
    volumes:
      - device_name: /dev/xvda
        device_type: standard
        volume_size: 8
        delete_on_termination: true
    assign_public_ip: yes
    monitoring: yes
  register: ec2

- name: "Wait for instances SSH to come up"
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances