- name: Remove backend server container
  sudo: yes
  docker:
    docker_api_version: "1.15"
    name: myapp
    image: quay.io/michaldec/myapp:1
    state: absent

- name: Recreate backend server container
  sudo: yes
  docker:
    name: myapp
    docker_api_version: "1.15"
    image: quay.io/michaldec/myapp:2
    net: host
    privileged: true
    ports: "8070:8070"
    registry: "{{ docker_registry }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
    pull: always
    restart_policy: always