---
- name: Add NGINX key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add Nginx repos
  apt_repository: repo='{{item}}' state=present
  with_items:
    - "deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
    - "deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
  when: ansible_architecture == "x86_64" and
    ansible_distribution == "Ubuntu" and
    ansible_distribution_release == "trusty"

- name: install latest NGINX package
  apt:  name=nginx  state=present

- name: add nginx user to www-data group
  user: name=nginx group=www-data
